version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test_user
      WORDPRESS_DB_PASSWORD: test_pass
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
 
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager] 
